spring.application.name=todolist-api

spring.datasource.url=jdbc:mysql://localhost:3306/todolist_db
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=${JWT_SECRET:minha-chave-secreta-temporaria-trocar-depois-1234567890}
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG